import Config

# Configure your database
config :mehungry, Mehungry.Repo,
  username: "postgres",
  password: "postgres",
  database: "mehungry_server_dev",
  hostname: "localhost",
  port: 5432,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  types: Mehungry.PostgrexTypes

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.

config :mehungry_local_ai, api_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYmMxMjNkZWY0NTYiLCJuYW1lIjoiVGVzdCBVc2VyIiwiaWF0IjoxNzg1NzI0ODAwLCJleHAiOjE3ODU3Mjg0MDB9.rX9gVvQh8L2N5pZcJ7Yw3eFaM1nSb6TdUk4Ai0XqLe8"


config :libcluster,
  topologies: [
    mehungry: [
      strategy: Elixir.Cluster.Strategy.LocalEpmd
    ]
  ]

config :mehungry_web, MehungryWeb.Endpoint,
  secret_key_base: "iH7KE2sUcWxfSctkWBtzxcSkJlSKZaVWP/hDKC8Hg3gCkGYZcXhIZLrEkzw/Ddq3",
  # http: [port: 4000],
  http: [ip: {127, 0, 0, 1}, port: System.get_env("PORT", "4000")],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  https: [
    port: System.get_env("HTTPS_PORT", "4001"),
    cipher_suite: :strong,
    keyfile: "priv/cert/selfsigned_key.pem",
    certfile: "priv/cert/selfsigned.pem"
  ],
  watchers: [
    esbuild:
      {Esbuild, :install_and_run,
       [:mehungry_web, ~w(--sourcemap=inline --watch --log-limit=0 --loader:.svg=file)]},
    tailwind: {Tailwind, :install_and_run, [:mehungry_web, ~w(--watch)]}
  ]

config :mehungry_web, MehungryWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/mehungry_web/(live|views)/.*(ex)$",
      ~r"lib/mehungry_web/templates/.*(eex)$"
    ]
  ]

# OAuth credentials for local development — override with real values via
# a local .env file or shell exports if you need to test OAuth flows.
config :ueberauth, Ueberauth.Strategy.Facebook.OAuth,
  client_id: System.get_env("FACEBOOK_CLIENT_ID"),
  client_secret: System.get_env("FACEBOOK_CLIENT_SECRET")

config :ueberauth, Ueberauth.Strategy.Google.OAuth,
  client_id: System.get_env("GOOGLE_CLIENT_ID"),
  client_secret: System.get_env("GOOGLE_CLIENT_SECRET")

config :ueberauth, Ueberauth.Strategy.Instagram.OAuth,
  client_id: System.get_env("INSTAGRAM_CLIENT_ID"),
  client_secret: System.get_env("INSTAGRAM_CLIENT_SECRET")

config :ueberauth, Ueberauth.Strategy.Pinterest.OAuth,
  client_id: System.get_env("PINTEREST_CLIENT_ID"),
  client_secret: System.get_env("PINTEREST_CLIENT_SECRET")

# Do not include metadata nor timestamps in development logs
config :logger, :console, level: :debug, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20
