import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
# config :mehungry, Mehungry.Repo,
# username: "postgres",
# password: "postgres",
#  database: "mehungry_server_dev",
#  hostname: "127.0.0.1",
#  port: 5432,
#  show_sensitive_data_on_connection_error: true,
#  pool_size: 10

config :mehungry_web, MehungryWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  check_origin: false,
  # force_ssl: [rewrite_on: [:x_forwarded_proto]],
  server: true,
  url: [host: "mehungry.com", port: 4000]

if config_env() == :prod do
  database_url = System.get_env("DATABASE_URL") ||
    raise """
      environment variable DATABASE_URL is missing.
    """

  maybe_ipv6 = if System.get_env("ECTO_IPV6") in ~w(true 1), do: [:inet6], else: []
  query_args = ["SET pg_trgm.similarity_threshold = 0.3", []]

  config :mehungry, Mehungry.Repo,
    url: database_url,
    pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10"),
    socket_options: maybe_ipv6,
    after_connect: {Postgrex, :query!, query_args}

  # config :mehungry, Mehungry.Repo,
  #  username: "postgres",
  #  password: "G2ET17z3N1243G",
  #  database: "mehungry_api_db",
  #  hostname: "mehungry-online-db.cwtjultszqbn.eu-west-3.rds.amazonaws.com",
  #  port: 5432,
  #  show_sensitive_data_on_connection_error: true,
  #  pool_size: 10

  # ## SSL Support
  #
  # To get SSL working, you will need to add the `https` key
  # to the previous section and set your `:url` port to 443:
  #
  #     config :mehungry_web, MehungryWeb.Endpoint,
  #       ...
  #       url: [host: "example.com", port: 443],
  #       https: [
  #         port: 443,
  #         cipher_suite: :strong,
  #         keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
  #         certfile: System.get_env("SOME_APP_SSL_CERT_PATH"),
  #         transport_options: [socket_opts: [:inet6]]
  #       ]
  #
  # The `cipher_suite` is set to `:strong` to support only the
  # latest and more secure SSL ciphers. This means old browsers
  # and clients may not be supported. You can set it to
  # `:compatible` for wider support.
  #
  # `:keyfile` and `:certfile` expect an absolute path to the key
  # and cert in disk or a relative path inside priv, for example
  # "priv/ssl/server.key". For all supported SSL configuration
  # options, see https://hexdocs.pm/plug/Plug.SSL.html#configure/1
  #
  # We also recommend setting `force_ssl` in your endpoint, ensuring
  # no data is ever sent via http, always redirecting to https:
  #
  #     config :mehungry_web, MehungryWeb.Endpoint,
  #       force_ssl: [hsts: true]
  #
  # Check `Plug.SSL` for all available options in `force_ssl`.

  # Do not print debug messages in production
  #
  #
  config :logger, level: :info
end
