import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
# config :mehungry, Mehungry.Repo,
# username: "postgres",
# password: "postgres",
#  database: "mehungry_server_dev",
#  hostname: "127.0.0.1",
#  port: 5432,
#  show_sensitive_data_on_connection_error: true,
#  pool_size: 10

config :libcluster,
  topologies: [
    ecs_dns: [
      strategy: Cluster.Strategy.DNSPoll,
      config: [
        # Check every 5s
        polling_interval: 1000,
        query: "discovery-service-m3hungry-ecs-backend.namespace-m3hungry-ecs-backend",
        node_basename: "mehungry_umbrella",
        app_name: :mehungry_umbrella
      ]
    ]
  ]

config :mehungry_web, MehungryWeb.Endpoint,
  http: [ip: {0, 0, 0, 0}, port: 4000],
  debug_errors: false,
  check_origin: false,
  # force_ssl: [rewrite_on: [:x_forwarded_proto]],
  server: true,
  # Canonical host. Keep this in sync with config/runtime.exs, which sets the
  # runtime scheme/port (https/443). Host must match so the session cookie is
  # scoped consistently (apex vs www would otherwise drop the session).
  url: [host: "www.m3hungry.com", port: 4000]
