[OUTPUT]
    Name cloudwatch_logs
    Match *
    region eu-central-1
    log_group_name /ecs/mehungry_app_deployment
    log_stream_prefix ecs/
    auto_create_group true

[OUTPUT]
    Name opentelemetry
    Match *
    Host nikolishome.duckdns.org
    Port 443
    uri /v1/logs
    tls on

    Header       Authorization Bearer ${ALLOY_LOG_TOKEN}
